---
AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'Vagrantfile'
    - 'Policyfile.rb'
    - 'Berksfile'
    - 'Thorfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'test/**/*'
    - 'bin/**'
    - 'vendor/**/*'
AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
---
AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/FileName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'
    - 'test/**/*'
    - 'bin/**'
    - 'vendor/**/*'

Style/GuardClause:
  Enabled: false
