name 'redhat'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Wrapper cookbook which configures RHEL systems.'
long_description 'Wrapper cookbook which configures RHEL systems.'
version '0.1.0'

supports 'centos', '>= 5.0'
supports 'redhat', '>= 5.0'
supports 'amazon'

depends 'yum'
depends 'yum-amazon'
depends 'yum-epel'
depends 'yum-centos'
